# Generated by Django 3.2.2 on 2021-05-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='magog_sensor',
            fields=[
                ('web_lon', models.FloatField()),
                ('web_lat', models.FloatField()),
                ('device_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'magog_sensor',
            },
        ),
        migrations.CreateModel(
            name='magog_uhi',
            fields=[
                ('device_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'magog_uhi',
                'unique_together': {('device_id', 'time', 'date')},
            },
        ),
    ]
